# Generated by Django 3.0.2 on 2020-12-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='username',
        ),
        migrations.AddField(
            model_name='book',
            name='applicant',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='club',
            field=models.CharField(max_length=20),
        ),
    ]
