# Generated by Django 3.0.2 on 2020-12-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
